<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace FulfilioNet\eBaySDK\Test\Browse\Enums;

use FulfilioNet\eBaySDK\Browse\Enums\AvailabilityStatusEnum;

class AvailabilityStatusEnumTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new AvailabilityStatusEnum();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\FulfilioNet\eBaySDK\Browse\Enums\AvailabilityStatusEnum', $this->obj);
    }
}
