<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace FulfilioNet\eBaySDK\Product\Services;

class ProductService extends \FulfilioNet\eBaySDK\Product\Services\ProductBaseService
{
    const API_VERSION = '1.4.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\FindProductsRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\FindProductsResponse
     */
    public function findProducts(\FulfilioNet\eBaySDK\Product\Types\FindProductsRequest $request)
    {
        return $this->findProductsAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\FindProductsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProductsAsync(\FulfilioNet\eBaySDK\Product\Types\FindProductsRequest $request)
    {
        return $this->callOperationAsync(
            'findProducts',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\FindProductsResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\FindProductsByCompatibilityRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\FindProductsResponse
     */
    public function findProductsByCompatibility(\FulfilioNet\eBaySDK\Product\Types\FindProductsByCompatibilityRequest $request)
    {
        return $this->findProductsByCompatibilityAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\FindProductsByCompatibilityRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findProductsByCompatibilityAsync(\FulfilioNet\eBaySDK\Product\Types\FindProductsByCompatibilityRequest $request)
    {
        return $this->callOperationAsync(
            'findProductsByCompatibility',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\FindProductsResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\GetProductDetailsRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\GetProductDetailsResponse
     */
    public function getProductDetails(\FulfilioNet\eBaySDK\Product\Types\GetProductDetailsRequest $request)
    {
        return $this->getProductDetailsAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\GetProductDetailsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductDetailsAsync(\FulfilioNet\eBaySDK\Product\Types\GetProductDetailsRequest $request)
    {
        return $this->callOperationAsync(
            'getProductDetails',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\GetProductDetailsResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\GetProductCompatibilitiesRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\GetProductCompatiblitiesResponse
     */
    public function getProductCompatibilities(\FulfilioNet\eBaySDK\Product\Types\GetProductCompatibilitiesRequest $request)
    {
        return $this->getProductCompatibilitiesAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\GetProductCompatibilitiesRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductCompatibilitiesAsync(\FulfilioNet\eBaySDK\Product\Types\GetProductCompatibilitiesRequest $request)
    {
        return $this->callOperationAsync(
            'getProductCompatibilities',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\GetProductCompatiblitiesResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\FindCompatibilitiesBySpecificationRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\FindCompatibilitiesBySpecificationResponse
     */
    public function findCompatibilitiesBySpecification(\FulfilioNet\eBaySDK\Product\Types\FindCompatibilitiesBySpecificationRequest $request)
    {
        return $this->findCompatibilitiesBySpecificationAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\FindCompatibilitiesBySpecificationRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findCompatibilitiesBySpecificationAsync(\FulfilioNet\eBaySDK\Product\Types\FindCompatibilitiesBySpecificationRequest $request)
    {
        return $this->callOperationAsync(
            'findCompatibilitiesBySpecification',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\FindCompatibilitiesBySpecificationResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\AddProductsRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\AddProductsResponse
     */
    public function addProducts(\FulfilioNet\eBaySDK\Product\Types\AddProductsRequest $request)
    {
        return $this->addProductsAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\AddProductsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function addProductsAsync(\FulfilioNet\eBaySDK\Product\Types\AddProductsRequest $request)
    {
        return $this->callOperationAsync(
            'addProducts',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\AddProductsResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\GetProductSubmissionsRequest $request
     * @return \FulfilioNet\eBaySDK\Product\Types\GetProductSubmissionsResponse
     */
    public function getProductSubmissions(\FulfilioNet\eBaySDK\Product\Types\GetProductSubmissionsRequest $request)
    {
        return $this->getProductSubmissionsAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\Product\Types\GetProductSubmissionsRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getProductSubmissionsAsync(\FulfilioNet\eBaySDK\Product\Types\GetProductSubmissionsRequest $request)
    {
        return $this->callOperationAsync(
            'getProductSubmissions',
            $request,
            '\FulfilioNet\eBaySDK\Product\Types\GetProductSubmissionsResponse'
        );
    }
}
