<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace FulfilioNet\eBaySDK\FileTransfer\Services;

class FileTransferService extends \FulfilioNet\eBaySDK\FileTransfer\Services\FileTransferBaseService
{
    const API_VERSION = '1.1.0';

    /**
     * @param array $config Configuration option values.
     */
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    /**
     * @param \FulfilioNet\eBaySDK\FileTransfer\Types\UploadFileRequest $request
     * @return \FulfilioNet\eBaySDK\FileTransfer\Types\UploadFileResponse
     */
    public function uploadFile(\FulfilioNet\eBaySDK\FileTransfer\Types\UploadFileRequest $request)
    {
        return $this->uploadFileAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\FileTransfer\Types\UploadFileRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function uploadFileAsync(\FulfilioNet\eBaySDK\FileTransfer\Types\UploadFileRequest $request)
    {
        return $this->callOperationAsync(
            'uploadFile',
            $request,
            '\FulfilioNet\eBaySDK\FileTransfer\Types\UploadFileResponse'
        );
    }

    /**
     * @param \FulfilioNet\eBaySDK\FileTransfer\Types\DownloadFileRequest $request
     * @return \FulfilioNet\eBaySDK\FileTransfer\Types\DownloadFileResponse
     */
    public function downloadFile(\FulfilioNet\eBaySDK\FileTransfer\Types\DownloadFileRequest $request)
    {
        return $this->downloadFileAsync($request)->wait();
    }

    /**
     * @param \FulfilioNet\eBaySDK\FileTransfer\Types\DownloadFileRequest $request
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function downloadFileAsync(\FulfilioNet\eBaySDK\FileTransfer\Types\DownloadFileRequest $request)
    {
        return $this->callOperationAsync(
            'downloadFile',
            $request,
            '\FulfilioNet\eBaySDK\FileTransfer\Types\DownloadFileResponse'
        );
    }
}
