<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace FulfilioNet\eBaySDK\Test\PostOrder\Types;

use FulfilioNet\eBaySDK\PostOrder\Types\SearchReturnsRestResponse;

class SearchReturnsRestResponseTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new SearchReturnsRestResponse();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\FulfilioNet\eBaySDK\PostOrder\Types\SearchReturnsRestResponse', $this->obj);
    }

    public function testExtendsGetSummaryResponse()
    {
        $this->assertInstanceOf('\FulfilioNet\eBaySDK\PostOrder\Types\GetSummaryResponse', $this->obj);
    }
}
